Add manifest source option
ResultadosDigitais/feature_flagger pull request #88
Opened 2021-12-03 15:08 UTC by miclain

## O que foi feito:
- Inclusão de métodos para opções de armazenamento e carregamento do arquivo rollout.yml (com o arquivo; com o arquivo gerando backup em storage; somente storage)
- Testes para os métodos criados e ajustes dos testes existentes
- Atualização da versão da gem
- Atualização do readme

## Como testar:
- Comando `bundle exec rspec`

2021-12-03 15:24 UTC, nandosousafr commented on README.md
> +There is a few options to storage your file rollout.yml:
```suggestion
There are a few options to store/retrieve your rollout manifest (a.k.a rollout.yml):
```

2021-12-03 15:24 UTC, nandosousafr commented on README.md
> +If you already have your file on redis and prefer not to keep a copy in your application, add the folow code to the configuration box:
```suggestion
If you already have your manifest on Redis and prefer not to keep a copy in your application, add the following code to the configuration block:
```

2021-12-03 15:25 UTC, nandosousafr commented on README.md
> +If you have a rollout.yml file and want to use redis to keep a backup, add the folow code to the configuration box:
```suggestion
If you have a rollout.yml file and want to use Redis to keep a backup, add the follow code to the configuration block:
```

2021-12-03 15:26 UTC, nandosousafr commented on README.md
> +If have the file and don't need a backup, is not necessary to do any different configuration.
```suggestion
If you have the YAML file and don't need a backup, it is unnecessary to do any different configuration.
```

2021-12-03 15:32 UTC, nandosousafr commented on spec/feature_flagger/feature_spec.rb
> +      allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
  FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

be careful with mocks.

2021-12-03 15:32 UTC, nandosousafr commented on spec/feature_flagger/manager_spec.rb
> +        allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
        yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
        FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:32 UTC, nandosousafr commented on spec/feature_flagger/manager_spec.rb
> +          allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
          yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
          FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:33 UTC, nandosousafr commented on spec/feature_flagger/manager_spec.rb
> +          allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
          yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
          FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:33 UTC, nandosousafr commented on spec/feature_flagger/model_spec.rb
> +      allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
      yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
      FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:33 UTC, nandosousafr commented on spec/feature_flagger/model_spec.rb
> +        allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
        yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
        FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:33 UTC, nandosousafr commented on spec/feature_flagger/model_spec.rb
> +          allow(FeatureFlagger.config).to receive(:info).and_return(YAML.load_file(yaml_path))
```suggestion
          yaml_path = File.expand_path('../../fixtures/rollout_example.yml', __FILE__)
          FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:34 UTC, nandosousafr commented on spec/feature_flagger/storage/feature_keys_migration_spec.rb
> +    FeatureFlagger.config.manifest_source = yaml_path
```suggestion
    yaml_path = File.expand_path('../fixtures/rollout_example.yml', __dir__)
    FeatureFlagger.config.manifest_source = FeatureFlagger::ManifestSources::WithYamlFile.new(yaml_path)
```

2021-12-03 15:34 UTC, nandosousafr commented on spec/manifests/with_yaml_file_spec.rb
> +		end
wrong identation

2021-12-03 15:34 UTC, nandosousafr commented on spec/manifests/yaml_with_backup_to_storage_spec.rb
> +	  end
wrong identation

2021-12-03 15:35 UTC, nandosousafr requested changes
nice work 🎉 

I've just asked for a few changes.

2021-12-03 16:48 UTC, miclain commented on spec/manifests/storage_only_spec.rb
> +	  end
done

2021-12-03 16:48 UTC, miclain commented on spec/manifests/with_yaml_file_spec.rb
> +		end
done

2021-12-03 16:48 UTC, miclain commented on spec/manifests/yaml_with_backup_to_storage_spec.rb
> +	  end
done

2021-12-14 12:38 UTC, angeliski approved these changes

2021-12-14 12:49 UTC, nandosousafr approved these changes

2021-12-16 18:32 UTC, merged

2021-12-20 15:58 UTC, andrehjr commented on spec/manifests/yaml_with_backup_to_storage_spec.rb
> +require 'feature_flagger/manifest_sources/yaml_with_backup_to_storage'
Why these new manifest_sources are not required by default?